[mgr]
prepend_keymap = [
	# Navigation
	{ on = ["g", "d"], run = "cd ~/Documents", desc = "Go ~/Documents" },
	{ on = ["g", "D"], run = "cd ~/Downloads", desc = "Go ~/Downloads" },
	{ on = ["g", "p"], run = "cd ~/Pictures", desc = "Go ~/Pictures" },
	{ on = ["g", "v"], run = "cd ~/Videos", desc = "Go ~/Videos" },
	{ on = ["g", "m"], run = "cd ~/Music", desc = "Go ~/Music" },

	# Trash Management
	{ on = ["g", "T"], run = "plugin recycle-bin -- open", desc = "Open Trash" },
	{ on = ["T", "e"], run = "plugin recycle-bin -- empty", desc = "Empty Trash" },
	{ on = ["T", "d"], run = "plugin recycle-bin -- delete", desc = "Delete from Trash" },
	{ on = ["T", "r"], run = "plugin recycle-bin -- restore", desc = "Restore from Trash" },

	# Mount Management
	{ on = "M", run = "plugin mount", desc = "Open Mount Manager" },

	# Compress
	{ on = ["c", "a", "a"], run = "plugin compress", desc = "Archive selected files and folders" },
	{ on = ["c", "a", "p"], run = "plugin compress -p", desc = "Archive selected files and folders (password)" },
]
